### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by xtrasmal** [sohelamin/laravel-crud-generator#1]
Hi there,

You should make it a composer package

**Comment by sohelamin** [comment]
Hi @xtrasmal ,

Thanks for your feedback will do very soon. It's on progress.
And let me know, how it works for your cases.

Sohel Amin

**Comment by xtrasmal** [comment]
I think I'll try it out this week on a rush project.

**Comment by sohelamin** [comment]
I appreciate that and also I will be pleased if you use and like it.
Cheers man :)

**Comment by sohelamin** [comment]
Hi @xtrasmal ,

I've published a package for it so you won't worry about to use it.
Please check it out from here https://packagist.org/packages/appzcoder/crud-generator
And for instructions https://github.com/appzcoder/crud-generator

Thanks
Sohel Amin
